const data = [
  {
    id: 1,
    imgLink: 'https://i.redd.it/i0z3l6fl9i331.jpg',
    price: 29.99,
    product: 'T-shirt',
    name: 'Basic T-shirt',
    category: 'Clothing',
    brand: 'Generic Brand',
  },
  {
    id: 2,
    imgLink: 'https://i.redd.it/i0z3l6fl9i331.jpg',
    price: 49.99,
    product: 'Shoes',
    name: 'Running Shoes',
    category: 'Footwear',
    brand: 'Sporty Brand',
  },
  {
    id: 3,
    imgLink: 'https://i.redd.it/i0z3l6fl9i331.jpg',
    price: 9.99,
    product: 'Socks',
    name: 'Cotton Socks',
    category: 'Clothing',
    brand: 'Comfy Brand',
  },
  {
    id: 4,
    imgLink: 'https://i.redd.it/i0z3l6fl9i331.jpg',
    price: 10.23,
    product: 'Underwear',
    name: 'Glen Underwear',
    category: 'Clothing',
    brand: 'Verserce',
  },
  {
    id: 5,
    imgLink: 'https://i.redd.it/i0z3l6fl9i331.jpg',
    price: 10.23,
    product: 'Underwear',
    name: 'Glen Underwear',
    category: 'Clothing',
    brand: 'Verserce',
  },
  {
    id: 6,
    imgLink: 'https://i.redd.it/i0z3l6fl9i331.jpg',
    price: 10.23,
    product: 'Underwear',
    name: 'Glen Underwear',
    category: 'Clothing',
    brand: 'Verserce',
  },
  {
    id: 7,
    imgLink: 'https://i.redd.it/i0z3l6fl9i331.jpg',
    price: 10.23,
    product: 'Underwear',
    name: 'Glen Underwear',
    category: 'Clothing',
    brand: 'Verserce',
  },
];

// module.exports = data;
export default data;
